### PR TITLE
Rancher k8s updates

### PR DESCRIPTION
**Pull request by ericbo**
* Added a quick disclaimer for those using newer version of k8s/k3s.
* Bumped up the release of cert-manager to `1.1.0` from `1.0.4`.
* Added a quick troubleshooting step for `helm install`.

### CODE REVIEW

**Comment by timothystewart6** [comment]
looks like there merge conflicts now

**Comment by timothystewart6** [comment]
@ericbo these will need to be resolved before merging.  Thank you!

**Comment by ericbo** [comment]
@timothystewart6 conflicts have been resolved. Happy I could contribute.

**Comment by timothystewart6** [comment]
Thank you!  Hopefully we can remove this soon (after k8s `1.20` support)  but this is a great solution in the interim.  Thank you!

**Pull request merged**
